comment:
  image:
    repository: knuteg/comment
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: serboox/post
    tag: latest
  service:
    externalPort: 5000

ui:
  image:
    repository: knuteg/ui
    tag: latest
  service:
    externalPort: 9292