version: '3.3'
services:
 
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - 9090:9090/tcp
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      back_net:
        aliases:
          - prometheus
      front_net:
        aliases:
          - prometheus

  node_exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    ports:
      - 9100:9100/tcp
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      back_net:
        aliases:
          - node_exporter
      front_net:
        aliases:
          - node_exporter

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      back_net:
        aliases:
          - cadvisor
      front_net:
        aliases:
          - cadvisor

volumes:
  prometheus_data:
    
networks:
  front_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${network_front}
  back_net:
    driver: bridge
    ipam:
      driver: default 
      config:
        - subnet: ${network_back}
        # 10.0.2.0/24